### ISSUE TITLE
[Release]: Propose Milestone 2

### ISSUE THREAD

**Issue by KyleAure** [jakartaee/data#356]
### Proposal

Since Milestone 1 there have been API changes.
So it would be a good idea to have a Milestone 2 release put out so implementations can start using the semi-final API.

Goal: Deploy Milestone 2 on ~Friday, November 24th 2023~ Monday, November 27th 2023

### Outstanding work

> These are the outstanding issues that are tagged for Jakarta EE 11

- [ ] https://github.com/jakartaee/data/issues/353
- [ ] https://github.com/jakartaee/data/issues/228
- [x] https://github.com/jakartaee/data/issues/133
- [x] https://github.com/jakartaee/data/issues/361

#### Prepare
  - [X] Open this issue.
  - [x] Complete outstanding work
  - [x] (Update TCK Signatures to capture API changes)[https://github.com/jakartaee/data/blob/main/tck/src/main/java/ee/jakarta/tck/data/framework/signature/README.md#generating-the-signature-file]
#### Stage release
  - [x] [Update the CHANGELOG.adoc file to reflect the changes put into the new release](https://github.com/jakartaee/data/blob/main/CHANGELOG.adoc)
  - [x] [Build and stage artifacts to staging repository](https://ci.eclipse.org/data/view/Release%20Builds/job/jakarta-data-build-and-stage/)
  - [x] [Build and stage the TCK distribution artifact to download.eclipse.org](https://ci.eclipse.org/data/view/Eclipse%20Builds/job/jakarta-data-tck-build-and-stage/)
  - [x] Update this issue with a comment that links to the staged artifacts and the generated GitHub branch and tag
  - [x] [Create a `pre-release` on GitHub](https://github.com/jakartaee/data/releases/new)
#### Verify and modify
  - [x] Ask for feedback from the community to verify the staged artifact has all the expected changes.
  - [x] If anything needs to be added before publishing do that now and repeat the `Stage Release` section
#### Publish release
  - [x] [Publish staged artifacts to the public repository](https://ci.eclipse.org/data/view/Release%20Builds/job/jakarta-data-stage-to-release/)
  - [x] [Publish staged TCK distribution artifact to download.eclipse.org](https://ci.eclipse.org/data/view/Eclipse%20Builds/job/jakarta-data-tck-staged-to-promoted/)
  - [ ] Update this issue with a comment that links to the published artifacts and the generated GitHub branch and tag
  - [x] [Modify the `pre-release` on GitHub to be `latest`](https://github.com/jakartaee/data/releases)
#### Follow up
  - [x] [Email a Jakarta steering committee member to promote the TCK Distribution publically](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/)
  - [x] Update versions in non-build files, such as:
    Documentation:
    - [README.adoc](https://github.com/jakartaee/data/blob/main/README.adoc)
    - [data-tck-reference-guide.adoc](https://github.com/jakartaee/data/blob/main/tck-dist/src/main/asciidoc/data-tck-reference-guide.adoc)

**Comment by KyleAure** [comment]
Milestone 2 is staged:

- GitHub Tag: https://github.com/jakartaee/data/releases/tag/1.0.0-M2
- GitHub Branch: https://github.com/jakartaee/data/tree/RELEASE-1.0.0-M2
- GitHub Prerelease: https://github.com/jakartaee/data/releases/tag/1.0.0-M2
- Staging repo: https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/data/

Please review the Milestone 2 staged release and comment on this issue if there are any additions/deletions needed before we go forward with publishing the Milestone 1 release

**Comment by otaviojava** [comment]
Thank you @KyleAure after all the merged, we are ready to go.

**Comment by KyleAure** [comment]
Updated staged Milestone 2: 

To include the artifact name change

- GitHub Tag: https://github.com/jakartaee/data/tree/1.0.0-M2
- GitHub Branch: https://github.com/jakartaee/data/tree/RELEASE-1.0.0-M2
- GitHub Prerelease: https://github.com/jakartaee/data/releases/tag/1.0.0-M2
- Staging repo: https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/data/
- To-be-released: https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1014/jakarta/data/

@otaviojava go ahead and review that everything looks correct and I can go ahead and publish the release.

**Comment by otaviojava** [comment]
@KyleAure could you include the bug that you found at this one?

**Comment by KyleAure** [comment]
Updated staged Milestone 2: 

To include the correct copyright in the Spec document

- GitHub Tag: https://github.com/jakartaee/data/tree/1.0.0-M2
- GitHub Branch: https://github.com/jakartaee/data/tree/RELEASE-1.0.0-M2
- GitHub Prerelease: https://github.com/jakartaee/data/releases/tag/1.0.0-M2
- Staging repo: https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/data/
- To-be-released: https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1015/jakarta/data/

FYI - @otaviojava

**Comment by otaviojava** [comment]
IMHO: we are ready to go. @njr-11 ?

**Comment by KyleAure** [comment]
Milestone 2 released: 

- GitHub Tag: https://github.com/jakartaee/data/tree/1.0.0-M2
- GitHub Branch: https://github.com/jakartaee/data/tree/RELEASE-1.0.0-M2
- GitHub Release: https://github.com/jakartaee/data/releases/tag/1.0.0-M2
- Release repo: https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/data/
- Maven Central: https://repo1.maven.org/maven2/jakarta/data/
