### ISSUE TITLE
[Release]: Milestone 1.0.0-M3

### ISSUE THREAD

**Issue by KyleAure** [jakartaee/data#415]
### Proposal

There have been additional changes to the API and TCK that will require an additional milestone release.

### Outstanding work

- [x] #413 
- [x] #414 
- [x] #411
- [x] #410 
- [x] #394
- [x] #421
- [x] #432

Anything else we need to go into Milestone 3?

#### Prepare
  - [X] Open this issue.
  - [x] Complete outstanding work
  - [x] (Update TCK Signatures to capture API changes)[https://github.com/jakartaee/data/actions/workflows/release.yml]
#### Stage release
  - [x] [Update the CHANGELOG.adoc file to reflect the changes put into the new release](https://github.com/jakartaee/data/blob/main/CHANGELOG.adoc)
  - [x] [Build and stage artifacts to staging repository](https://ci.eclipse.org/data/view/Release%20Builds/job/jakarta-data-build-and-stage/)
  - [x] [Build and stage the TCK distribution artifact to download.eclipse.org](https://ci.eclipse.org/data/view/Eclipse%20Builds/job/jakarta-data-tck-build-and-stage/)
  - [x] Update this issue with a comment that links to the staged artifacts and the generated GitHub branch and tag
  - [x] [Create a `pre-release` on GitHub](https://github.com/jakartaee/data/releases/new)
#### Verify and modify
  - [x] Ask for feedback from the community to verify the staged artifact has all the expected changes.
  - [x] If anything needs to be added before publishing do that now and repeat the `Stage Release` section
#### Publish release
  - [x] [Publish staged artifacts to the public repository](https://ci.eclipse.org/data/view/Release%20Builds/job/jakarta-data-stage-to-release/)
  - [x] [Publish staged TCK distribution artifact to download.eclipse.org](https://ci.eclipse.org/data/view/Eclipse%20Builds/job/jakarta-data-tck-staged-to-promoted/)
  - [x] Update this issue with a comment that links to the published artifacts and the generated GitHub branch and tag
  - [x] [Modify the `pre-release` on GitHub to be `latest`](https://github.com/jakartaee/data/releases)
#### Follow up
  - [x] [Email a Jakarta steering committee member to promote the TCK Distribution publically](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/)
  - [x] Update versions in non-build files, such as:
    Documentation:
    - [README.adoc](https://github.com/jakartaee/data/blob/main/README.adoc)
    - [data-tck-reference-guide.adoc](https://github.com/jakartaee/data/blob/main/tck-dist/src/main/asciidoc/data-tck-reference-guide.adoc)

**Comment by njr-11** [comment]
Excellent idea to create a Milestone 3 given the update! We should have a final answer regarding the last issue in the list, #394, on Wednesday, Jan 17 if everyone attends the Jakarta Data meeting that day.

**Comment by KyleAure** [comment]
Milestone 3 is staged:

- GitHub Tag: [1.0.0-M3](https://github.com/jakartaee/data/tree/1.0.0-M3)
- GitHub Branch: [RELEASE-1.0.0-M3](https://github.com/jakartaee/data/tree/RELEASE-1.0.0-M3)
- GitHub Prerelease: [1.0.0-M3](https://github.com/jakartaee/data/releases/tag/1.0.0-M3)
- Staging repo: [jakartadata-1016](https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1016/jakarta/data/)

**Comment by KyleAure** [comment]
Milestone 3 is re-staged:

- GitHub Tag: [1.0.0-M3](https://github.com/jakartaee/data/tree/1.0.0-M3)
- GitHub Branch: [RELEASE-1.0.0-M3](https://github.com/jakartaee/data/tree/RELEASE-1.0.0-M3)
- GitHub Prerelease: [1.0.0-M3](https://github.com/jakartaee/data/releases/tag/1.0.0-M3)
- Staging repo: [jakartadata-1017](https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1017/)

FYI - @njr-11 @otaviojava let me know if this looks good and I go ahead and publish the release.

**Comment by lprimak** [comment]
Please use "Release Drafts" to indicate that the release is not public. Currently, it looks like M3 is released on GitHub but it's not in Maven Central. 

Tank you!

**Comment by KyleAure** [comment]
@lprimak I put the release as `pre-release` I figured that would indicate it hasn't been released yet. Perhaps I misunderstood what the use case of `pre-release` would be.

**Comment by lprimak** [comment]
Either you or me :)
I always thought that `pre-release` was alpha, beta, etc. and it's all "deployed" in central but not considered a "final" release.

**Comment by KyleAure** [comment]
Ahh.  I can change this process to use drafts instead.  I assume you get a notification if I mark it pre-release?

**Comment by lprimak** [comment]
Thanks Kyle!
Yes, I got a notification and assumed that it was (or would shortly be) on Maven Central.
I also updated Jakarta EE platform to use it.
Is M3 going to be released soon or would I need to revert the Jakarta EE platform change to use M2 instead?
If M3 going to be released soon, I will just leave it alone as Platform M2 isn't scheduled for another few weeks I think

**Comment by KyleAure** [comment]
I believe there is just [one more doc change](https://github.com/jakartaee/data/pull/474) that needs to go in and then I'll go forward with a stage/release.

**Comment by gavinking** [comment]
@KyleAure I don't think #474 needs to block the release. We have not reached consensus on it.

**Comment by KyleAure** [comment]
Milestone 3 is re-staged:

- GitHub Tag: [1.0.0-M3](https://github.com/jakartaee/data/tree/1.0.0-M3)
- GitHub Branch: [RELEASE-1.0.0-M3](https://github.com/jakartaee/data/tree/RELEASE-1.0.0-M3)
- GitHub Release (DRAFT): [1.0.0-M3](https://github.com/jakartaee/data/releases/tag/untagged-c46fa3c5887b5a312de6)
- Staging repo: [jakartadata-1018](https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1018/)

FYI - @gavinking @otaviojava @njr-11 @lprimak I'll test this against Open Liberty tomorrow and push to maven central so long as there are no other changes y'all want to be put in (that can't wait for M4)

**Comment by KyleAure** [comment]
Milestone 3 is released 🚀 :

- GitHub Tag: [1.0.0-M3](https://github.com/jakartaee/data/tree/1.0.0-M3)
- GitHub Branch: [RELEASE-1.0.0-M3](https://github.com/jakartaee/data/tree/RELEASE-1.0.0-M3)
- GitHub Release (pre-release): [1.0.0-M3](https://github.com/jakartaee/data/releases/tag/1.0.0-M3)
- Maven Central: [jakarta.data-api](https://repo1.maven.org/maven2/jakarta/data/jakarta.data-api/)

**Comment by gavinking** [comment]
Nice!

And now that it's available, I have already made an excellent start on an implementation!

The main challenge is going to be the keyset-based pagination stuff.
