### ISSUE TITLE
[Release]: 1.0.0-RC1

### ISSUE THREAD

**Issue by KyleAure** [jakartaee/data#631]
### Proposal

Need to do an RC1 release for Jakarta Data by April 19th based on agreement here:  #516

### Outstanding work

Issues:
- [x] #516 - includes todo for query language TCK tests
- [x] #529 
- [x] #576 
- [x] #603 
- [x] #622 
- [x] #705 
- [x] #700

Pulls:
- [x] #625 
- [x] #599 -> Jakarta Data Next
- [x] #616 - Fix and then we can merge

Future Items: 
- [x] Deprecate Query by Method Name
- [x] Query by Method Name into separate spec file

#### Prepare
  - [X] Open this issue.
  - [x] Complete outstanding work
  - [x] [Update TCK Signatures to capture API changes](https://github.com/jakartaee/data/actions/workflows/update.yml)
#### Stage release
  - [x] [Update the CHANGELOG.adoc file to reflect the changes put into the new release](https://github.com/jakartaee/data/blob/main/CHANGELOG.adoc)
  - [x] [Build and stage artifacts to staging repository](https://ci.eclipse.org/data/view/Release%20Builds/job/jakarta-data-build-and-stage/)
  - [x] [Build and stage the TCK distribution artifact to download.eclipse.org](https://ci.eclipse.org/data/view/Eclipse%20Builds/job/jakarta-data-tck-build-and-stage/)
  - [x] Update this issue with a comment that links to the staged artifacts and the generated GitHub branch and tag
  - [x] [Create a `draft` release on GitHub](https://github.com/jakartaee/data/releases/new)
#### Verify and modify
  - [x] Ask for feedback from the community to verify the staged artifact has all the expected changes.
  - [x] If anything needs to be added before publishing do that now and repeat the `Stage Release` section
#### Publish release
  - [x] [Publish staged artifacts to the public repository](https://ci.eclipse.org/data/view/Release%20Builds/job/jakarta-data-stage-to-release/)
  - [x] [Publish staged TCK distribution artifact to download.eclipse.org](https://ci.eclipse.org/data/view/Eclipse%20Builds/job/jakarta-data-tck-staged-to-promoted/)
  - [x] Update this issue with a comment that links to the published artifacts and the generated GitHub branch and tag
  - [x] [Modify the `draft` release on GitHub to be `pre-release` or `latest`](https://github.com/jakartaee/data/releases)
#### Follow up
  - [x] [Email a Jakarta steering committee member to promote the TCK Distribution publically](https://ci.eclipse.org/jakartaee-spec-committee/job/promote-release/)
  - [x] Update versions in non-build files, such as:
    Documentation:
    - [README.adoc](https://github.com/jakartaee/data/blob/main/README.adoc)
    - [data-tck-reference-guide.adoc](https://github.com/jakartaee/data/blob/main/tck-dist/src/main/asciidoc/data-tck-reference-guide.adoc)

**Comment by KyleAure** [comment]
Release Candidate 1 is staged: 

- GitHub Tag: [1.0.0-RC1](https://github.com/jakartaee/data/tree/1.0.0-RC1)
- GitHub Branch: [RELEASE-1.0.0-RC1](https://github.com/jakartaee/data/tree/RELEASE-1.0.0-RC1)
- GitHub Release DRAFT: [1.0.0-RC1](https://github.com/jakartaee/data/releases/edit/untagged-8a1e201d98e7a362c3dc)
- Staging Repo: [jakartadata-1021](https://jakarta.oss.sonatype.org/content/repositories/jakartadata-1021/)

**Comment by KyleAure** [comment]
Release Candidate 1 is published: 

- GitHub Tag: [1.0.0-RC1](https://github.com/jakartaee/data/tree/1.0.0-RC1)
- GitHub Branch: [RELEASE-1.0.0-RC1](https://github.com/jakartaee/data/tree/RELEASE-1.0.0-RC1)
- GitHub Release: [1.0.0-RC1](https://github.com/jakartaee/data/releases/tag/1.0.0-RC1)
- Maven Central: [jakarta.data-api](https://repo1.maven.org/maven2/jakarta/data/jakarta.data-api/)
